# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  - main

pool:
  name: vt-pool

# strategy:
#   matrix:
#     Python38:
#       python.version: '3.8'
#     Python39:
#       python.version: '3.9'
#     Python310:
#       python.version: '3.10'
#     Python311:
#       python.version: '3.11'
#
steps:
  # - task: UsePythonVersion@0
  #   inputs:
  #     versionSpec: "$(python.version)"
  #   displayName: "Use Python $(python.version)"

  - script: |
      uname -a
      python3 --version
    displayName: "Env check"

  - script: |
      sudo apt update
      sudo apt -y install black
      sudo apt -y install pip
      pip -q install ruff
    displayName: "Prereqs"

  - script: |
      black --check . || echo "Black formatter error"
    displayName: "Black formatter"
  - script: |
      ruff check || echo "Ruff got errors"
    displayName: "Ruff"

  - script: |
      python3 -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install dependencies"
  - script: ./main.py --help
    displayName: "Test run"
  #
  # - script: |
  #     pip install pytest pytest-azurepipelines
  #     pytest
  #   displayName: "pytest"
